# Display a simple message
print("System Failure Imminent!")
print("System rboot has been initiated")
print("")
print("")
print("...rebooting sensory system")
print("...rebooting output motors")
print("...rebooting  hover engine")
print("")
print("")
print("System online.")
